### ISSUE TITLE
pretrained doc2vec link doesn't exist anymore

### ISSUE THREAD

**Issue by damienlancry** [sb1992/NETL-Automatic-Topic-Labelling-#10]
hello,

when I click on the link to the pre trained doc2vec document I end up on a page saying :
"This item might not exist or is no longer available"

**Comment by jhlau** [comment]
The pretrained models under https://github.com/sb1992/NETL-Automatic-Topic-Labelling-#pre-trained-models? Just checked and both doc2vec and word2vec links work for me.

**Comment by damienlancry** [comment]
yes I tried again it actually works

**Comment by damienlancry** [comment]
is this a dbow or a dpmv doc2vec? do you have more information about the hyperpamameters used ?

**Comment by damienlancry** [comment]
ok I just saw the answer in your paper:
"
we experiment only with dbow
doc2vec hyper-parameters: sub-sampling threshold = 10−5, vector size = 300, window size = 15, negative sample size = 5, and training epochs = 20.
"
