### ISSUE TITLE
Accessing the pretrained models and support files for training

### ISSUE THREAD

**Issue by sripirakas** [sb1992/NETL-Automatic-Topic-Labelling-#12]
Hi,

I would like to request access to the pre-trained models and additional support files that are now located in https://unimelbcloud-my.sharepoint.com. The files are currently not accessible and we get the error message: _That didn't work
We're sorry, but ******@*****.com can't be found in the unimelbcloud-my.sharepoint.com directory. Please try again later, while we try to automatically fix this for you_

The methods described in the paper and in the implementation are very interesting and we highly appreciate your assistance with it. Thanks.

Sri.

**Comment by jhlau** [comment]
Thanks for bringing this to our attention! Turns out those pesky onedrive links have a mandatory one-year expiry. I've now moved the files to another cloud storage and the links should work now.
